### PR TITLE
LAUREN: Add clothing item

### PR DESCRIPTION
**Pull request by madelesi**
I created a model for a closet  and then related the items together.

## General checklist before approving
- [x] Avoided changes that are not related to the pull request
- [x] Tests, if any, are passing
- [x] Merged main **into your branch first (not the other way around)**
- [x] Reviewed the checklist again **after the final changes and after merging main (or other upstream) into your branch**
- [x] Reasonable merge strategy (**avoid adding non-descriptive commits to main**)

### CODE REVIEW

**Comment by madelesi** [comment]
Most of this seems good, but a couple of things need to be done:
- ~~The relationship between items & closets has to be changed. Lookup implementing "one-to-many" in "FlaskSQLAlchemy"~~ Actually just do exactly what you did for "Closet & User" but for "ClothingItem & Closet" (& no need for the "closet_items" table)
- The api endpoint needs minor modifications: 
- It shouldn't take an argument (just use request.form to get the dict)
- and it should have "methods=..." POST instead of GET (you should remove the if-statement too)

**Comment by madelesi** [comment]
Note: Someone might have broken your old branch by mistake... But all your work has been copied over here & I copied my comments too

**Comment by laurencockey** [comment]
I'm trying to add miguel's changes to the branch, not yet ready for review

**Comment by madelesi** [comment]
Ready to merge.

**Review by cooperemily02 — APPROVED** [review]
Working great Lauren!! Thank you!!

**Pull request merged**
